[versions]
kotlin = "2.0.21"
springboot = "3.4.2"

[libraries]
springboot-bom = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "springboot" }
springboot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
springboot-starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
springboot = { id = "org.springframework.boot", version.ref = "springboot" }
