/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.12/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.kotlin.spring)
    alias(libs.plugins.springboot)
}

repositories {
    mavenCentral()
}

dependencies {
    implementation(platform(libs.springboot.bom))
    implementation(libs.springboot.starter.web)
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}
